sudo: required
language: ruby
rvm:
  - 2.2.6

services:
  - docker

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - gem install rubocop
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

script:
  - yarn lint
  - rubocop
