sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.1
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - yarn lint
  - bundle exec rubocop
  - bundle exec rake test
