sudo: required
language: ruby
rvm:
  - 2.2.6
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - yarn lint
