name: Ruby specs

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Ruby specs
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' || matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby:
          - 2.7
          - "3.0"
          - 3.1
          - 3.2
        gemfile:
          - gemfiles/Gemfile-rails.5.2.x
          - gemfiles/Gemfile-rails.6.0.x
          - gemfiles/Gemfile-rails.6.1.x
        exclude:
          - ruby: 2.5
            gemfile: gemfiles/Gemfile-rails.6.1.x
          - ruby: "3.0"
            gemfile: gemfiles/Gemfile-rails.5.2.x
          - ruby: 3.1
            gemfile: gemfiles/Gemfile-rails.5.2.x
          - ruby: 3.2
            gemfile: gemfiles/Gemfile-rails.5.2.x
        experimental: [false]
        include:
          - ruby: 2.7
            os: ubuntu-latest
            gemfile: gemfiles/Gemfile-rails-edge
            experimental: true
          - ruby: "3.0"
            os: ubuntu-latest
            gemfile: gemfiles/Gemfile-rails-edge
            experimental: true

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: latest
          bundler-cache: true # Run "bundle install", and cache the result automatically.

      - name: Ruby specs
        run: bundle exec rake
